security:
    enable_authenticator_manager: true
    firewalls:
      dev:
          pattern: ^/(_(profiler|wdt)|css|images|js)/
          security: false
      main:

    password_hashers:
      App\Entity\User:
            algorithm: auto

